# Generated by Django 5.2.4 on 2025-07-03 22:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('facilities', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='medicalfacility',
            name='slug',
            field=models.SlugField(default=1),
            preserve_default=False,
        ),
    ]
